### ISSUE TITLE
How can I run the test?

### ISSUE THREAD

**Issue by xueenda** [nunit/nunit-csharp-samples#14]
I am new to c#. Try to run the test. Where is the main function? Please advise.

Can you update the read me for some one new to c#?

**Comment by CharliePoole** [comment]
After building the test, you run the assembly that is created. Running tests is completely language-agnostic since it only deals with the output assembly.

For info on how to run the assembly using NUnit, see the general nunit documentation at https://github.com/nunit/docs/wiki

For information about how to write or compile C# code, there are many standard references or you can ask in a forum that's dedicated to that kind of question.
